#!/usr/bin/env bash
set -euo pipefail

cd "$(dirname "$0")/.."

tmp=$(mktemp)
trap 'rm -f "$tmp"' EXIT

.build/debug/MyttyCLI --experimental-dump-help | jq -r '
def fmt_option:
  if .preferredName == null then "<\(.valueName)>"
  else
    .preferredName as $pref |
    (if $pref.kind == "long" then "--" else "-" end) + $pref.name +
    ([(.names // [])[] | select(.kind != $pref.kind or .name != $pref.name) |
      (if .kind == "short" then "-" else "--" end) + .name] |
     if length > 0 then ", " + .[0] else "" end)
  end;

def fmt_args:
  [.[] | select(.valueName != "help" and .shouldDisplay != false) |
   "| \(fmt_option) | \(.abstract // "") | \(.defaultValue // "") |"] |
  if length > 0 then
    "\n| Option | Description | Default |\n| --- | --- | --- |\n" + join("\n") + "\n"
  else "" end;

"<!-- DO NOT EDIT. Generated by scripts/generate-cli-reference.sh -->\n\n# CLI Reference\n" +
([.command.subcommands[] | select(.commandName != "help") |
  . as $parent |
  "## mytty-cli \(.commandName)\n\n\(.abstract // "")\n" +
  ((.arguments // []) | fmt_args) +
  ([(.subcommands // [])[] | select(.commandName != "help") |
    "### mytty-cli \($parent.commandName) \(.commandName)\n\n\(.abstract // "")\n" +
    ((.arguments // []) | fmt_args)
  ] | join("\n"))
] | join("\n"))
' >"$tmp"

mv "$tmp" docs/CLI-REFERENCE.md
trap - EXIT
